# fly.toml app configuration file generated for eznashdb-worker on 2025-12-16T22:55:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eznashdb-worker'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  DJANGO_SETTINGS_MODULE = 'app.settings'
  TZ = 'Asia/Jerusalem'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
